CREATE USER auth WITH PASSWORD 'auth';
CREATE DATABASE auth OWNER auth;

CREATE USER animal WITH PASSWORD 'animal';
CREATE DATABASE animal OWNER animal;

CREATE USER billing WITH PASSWORD 'billing';
CREATE DATABASE billing OWNER billing;

CREATE USER chat WITH PASSWORD 'chat';
CREATE DATABASE chat OWNER chat;

CREATE USER feed WITH PASSWORD 'feed';
CREATE DATABASE feed OWNER feed;
