// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/analytics.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	FromRfc3339   string                 `protobuf:"bytes,2,opt,name=from_rfc3339,json=fromRfc3339,proto3" json:"from_rfc3339,omitempty"`
	ToRfc3339     string                 `protobuf:"bytes,3,opt,name=to_rfc3339,json=toRfc3339,proto3" json:"to_rfc3339,omitempty"`
	Bucket        string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_api_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetMetricsRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *GetMetricsRequest) GetFromRfc3339() string {
	if x != nil {
		return x.FromRfc3339
	}
	return ""
}

func (x *GetMetricsRequest) GetToRfc3339() string {
	if x != nil {
		return x.ToRfc3339
	}
	return ""
}

func (x *GetMetricsRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type MetricCounter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricCounter) Reset() {
	*x = MetricCounter{}
	mi := &file_api_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricCounter) ProtoMessage() {}

func (x *MetricCounter) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricCounter.ProtoReflect.Descriptor instead.
func (*MetricCounter) Descriptor() ([]byte, []int) {
	return file_api_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricCounter) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *MetricCounter) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ProfileMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	BucketRfc3339 string                 `protobuf:"bytes,2,opt,name=bucket_rfc3339,json=bucketRfc3339,proto3" json:"bucket_rfc3339,omitempty"`
	BucketSize    string                 `protobuf:"bytes,3,opt,name=bucket_size,json=bucketSize,proto3" json:"bucket_size,omitempty"`
	Counters      []*MetricCounter       `protobuf:"bytes,4,rep,name=counters,proto3" json:"counters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileMetric) Reset() {
	*x = ProfileMetric{}
	mi := &file_api_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileMetric) ProtoMessage() {}

func (x *ProfileMetric) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileMetric.ProtoReflect.Descriptor instead.
func (*ProfileMetric) Descriptor() ([]byte, []int) {
	return file_api_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileMetric) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ProfileMetric) GetBucketRfc3339() string {
	if x != nil {
		return x.BucketRfc3339
	}
	return ""
}

func (x *ProfileMetric) GetBucketSize() string {
	if x != nil {
		return x.BucketSize
	}
	return ""
}

func (x *ProfileMetric) GetCounters() []*MetricCounter {
	if x != nil {
		return x.Counters
	}
	return nil
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ProfileMetric       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_api_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetMetricsResponse) GetItems() []*ProfileMetric {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetExtendedStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	FromRfc3339   string                 `protobuf:"bytes,3,opt,name=from_rfc3339,json=fromRfc3339,proto3" json:"from_rfc3339,omitempty"`
	ToRfc3339     string                 `protobuf:"bytes,4,opt,name=to_rfc3339,json=toRfc3339,proto3" json:"to_rfc3339,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExtendedStatsRequest) Reset() {
	*x = GetExtendedStatsRequest{}
	mi := &file_api_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtendedStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtendedStatsRequest) ProtoMessage() {}

func (x *GetExtendedStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtendedStatsRequest.ProtoReflect.Descriptor instead.
func (*GetExtendedStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetExtendedStatsRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *GetExtendedStatsRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetExtendedStatsRequest) GetFromRfc3339() string {
	if x != nil {
		return x.FromRfc3339
	}
	return ""
}

func (x *GetExtendedStatsRequest) GetToRfc3339() string {
	if x != nil {
		return x.ToRfc3339
	}
	return ""
}

type GetExtendedStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProfileId      string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Views          int64                  `protobuf:"varint,2,opt,name=views,proto3" json:"views,omitempty"`
	Impressions    int64                  `protobuf:"varint,3,opt,name=impressions,proto3" json:"impressions,omitempty"`
	Ctr            float64                `protobuf:"fixed64,4,opt,name=ctr,proto3" json:"ctr,omitempty"`
	CardOpens      int64                  `protobuf:"varint,5,opt,name=card_opens,json=cardOpens,proto3" json:"card_opens,omitempty"`
	ChatStarts     int64                  `protobuf:"varint,6,opt,name=chat_starts,json=chatStarts,proto3" json:"chat_starts,omitempty"`
	Donations      int64                  `protobuf:"varint,7,opt,name=donations,proto3" json:"donations,omitempty"`
	Boosts         int64                  `protobuf:"varint,8,opt,name=boosts,proto3" json:"boosts,omitempty"`
	ProfileChanges int64                  `protobuf:"varint,9,opt,name=profile_changes,json=profileChanges,proto3" json:"profile_changes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetExtendedStatsResponse) Reset() {
	*x = GetExtendedStatsResponse{}
	mi := &file_api_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtendedStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtendedStatsResponse) ProtoMessage() {}

func (x *GetExtendedStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtendedStatsResponse.ProtoReflect.Descriptor instead.
func (*GetExtendedStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetExtendedStatsResponse) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *GetExtendedStatsResponse) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *GetExtendedStatsResponse) GetImpressions() int64 {
	if x != nil {
		return x.Impressions
	}
	return 0
}

func (x *GetExtendedStatsResponse) GetCtr() float64 {
	if x != nil {
		return x.Ctr
	}
	return 0
}

func (x *GetExtendedStatsResponse) GetCardOpens() int64 {
	if x != nil {
		return x.CardOpens
	}
	return 0
}

func (x *GetExtendedStatsResponse) GetChatStarts() int64 {
	if x != nil {
		return x.ChatStarts
	}
	return 0
}

func (x *GetExtendedStatsResponse) GetDonations() int64 {
	if x != nil {
		return x.Donations
	}
	return 0
}

func (x *GetExtendedStatsResponse) GetBoosts() int64 {
	if x != nil {
		return x.Boosts
	}
	return 0
}

func (x *GetExtendedStatsResponse) GetProfileChanges() int64 {
	if x != nil {
		return x.ProfileChanges
	}
	return 0
}

type GetRankingFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromRfc3339   string                 `protobuf:"bytes,1,opt,name=from_rfc3339,json=fromRfc3339,proto3" json:"from_rfc3339,omitempty"`
	ToRfc3339     string                 `protobuf:"bytes,2,opt,name=to_rfc3339,json=toRfc3339,proto3" json:"to_rfc3339,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankingFeedbackRequest) Reset() {
	*x = GetRankingFeedbackRequest{}
	mi := &file_api_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankingFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankingFeedbackRequest) ProtoMessage() {}

func (x *GetRankingFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankingFeedbackRequest.ProtoReflect.Descriptor instead.
func (*GetRankingFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_api_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetRankingFeedbackRequest) GetFromRfc3339() string {
	if x != nil {
		return x.FromRfc3339
	}
	return ""
}

func (x *GetRankingFeedbackRequest) GetToRfc3339() string {
	if x != nil {
		return x.ToRfc3339
	}
	return ""
}

func (x *GetRankingFeedbackRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RankingFeedback struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProfileId      string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	BucketRfc3339  string                 `protobuf:"bytes,2,opt,name=bucket_rfc3339,json=bucketRfc3339,proto3" json:"bucket_rfc3339,omitempty"`
	Ctr            float64                `protobuf:"fixed64,3,opt,name=ctr,proto3" json:"ctr,omitempty"`
	SwipeRightRate float64                `protobuf:"fixed64,4,opt,name=swipe_right_rate,json=swipeRightRate,proto3" json:"swipe_right_rate,omitempty"`
	Engagement     float64                `protobuf:"fixed64,5,opt,name=engagement,proto3" json:"engagement,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RankingFeedback) Reset() {
	*x = RankingFeedback{}
	mi := &file_api_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankingFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingFeedback) ProtoMessage() {}

func (x *RankingFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingFeedback.ProtoReflect.Descriptor instead.
func (*RankingFeedback) Descriptor() ([]byte, []int) {
	return file_api_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *RankingFeedback) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *RankingFeedback) GetBucketRfc3339() string {
	if x != nil {
		return x.BucketRfc3339
	}
	return ""
}

func (x *RankingFeedback) GetCtr() float64 {
	if x != nil {
		return x.Ctr
	}
	return 0
}

func (x *RankingFeedback) GetSwipeRightRate() float64 {
	if x != nil {
		return x.SwipeRightRate
	}
	return 0
}

func (x *RankingFeedback) GetEngagement() float64 {
	if x != nil {
		return x.Engagement
	}
	return 0
}

type GetRankingFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RankingFeedback     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankingFeedbackResponse) Reset() {
	*x = GetRankingFeedbackResponse{}
	mi := &file_api_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankingFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankingFeedbackResponse) ProtoMessage() {}

func (x *GetRankingFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankingFeedbackResponse.ProtoReflect.Descriptor instead.
func (*GetRankingFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_api_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *GetRankingFeedbackResponse) GetItems() []*RankingFeedback {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_analytics_proto protoreflect.FileDescriptor

const file_api_analytics_proto_rawDesc = "" +
	"\n" +
	"\x13api/analytics.proto\x12\fanalytics.v1\"\x8c\x01\n" +
	"\x11GetMetricsRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12!\n" +
	"\ffrom_rfc3339\x18\x02 \x01(\tR\vfromRfc3339\x12\x1d\n" +
	"\n" +
	"to_rfc3339\x18\x03 \x01(\tR\ttoRfc3339\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\tR\x06bucket\"D\n" +
	"\rMetricCounter\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"\xaf\x01\n" +
	"\rProfileMetric\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12%\n" +
	"\x0ebucket_rfc3339\x18\x02 \x01(\tR\rbucketRfc3339\x12\x1f\n" +
	"\vbucket_size\x18\x03 \x01(\tR\n" +
	"bucketSize\x127\n" +
	"\bcounters\x18\x04 \x03(\v2\x1b.analytics.v1.MetricCounterR\bcounters\"G\n" +
	"\x12GetMetricsResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.analytics.v1.ProfileMetricR\x05items\"\x8e\x01\n" +
	"\x17GetExtendedStatsRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12!\n" +
	"\ffrom_rfc3339\x18\x03 \x01(\tR\vfromRfc3339\x12\x1d\n" +
	"\n" +
	"to_rfc3339\x18\x04 \x01(\tR\ttoRfc3339\"\xa2\x02\n" +
	"\x18GetExtendedStatsResponse\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x14\n" +
	"\x05views\x18\x02 \x01(\x03R\x05views\x12 \n" +
	"\vimpressions\x18\x03 \x01(\x03R\vimpressions\x12\x10\n" +
	"\x03ctr\x18\x04 \x01(\x01R\x03ctr\x12\x1d\n" +
	"\n" +
	"card_opens\x18\x05 \x01(\x03R\tcardOpens\x12\x1f\n" +
	"\vchat_starts\x18\x06 \x01(\x03R\n" +
	"chatStarts\x12\x1c\n" +
	"\tdonations\x18\a \x01(\x03R\tdonations\x12\x16\n" +
	"\x06boosts\x18\b \x01(\x03R\x06boosts\x12'\n" +
	"\x0fprofile_changes\x18\t \x01(\x03R\x0eprofileChanges\"s\n" +
	"\x19GetRankingFeedbackRequest\x12!\n" +
	"\ffrom_rfc3339\x18\x01 \x01(\tR\vfromRfc3339\x12\x1d\n" +
	"\n" +
	"to_rfc3339\x18\x02 \x01(\tR\ttoRfc3339\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xb3\x01\n" +
	"\x0fRankingFeedback\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12%\n" +
	"\x0ebucket_rfc3339\x18\x02 \x01(\tR\rbucketRfc3339\x12\x10\n" +
	"\x03ctr\x18\x03 \x01(\x01R\x03ctr\x12(\n" +
	"\x10swipe_right_rate\x18\x04 \x01(\x01R\x0eswipeRightRate\x12\x1e\n" +
	"\n" +
	"engagement\x18\x05 \x01(\x01R\n" +
	"engagement\"Q\n" +
	"\x1aGetRankingFeedbackResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.analytics.v1.RankingFeedbackR\x05items2\xaf\x02\n" +
	"\x10AnalyticsService\x12O\n" +
	"\n" +
	"GetMetrics\x12\x1f.analytics.v1.GetMetricsRequest\x1a .analytics.v1.GetMetricsResponse\x12a\n" +
	"\x10GetExtendedStats\x12%.analytics.v1.GetExtendedStatsRequest\x1a&.analytics.v1.GetExtendedStatsResponse\x12g\n" +
	"\x12GetRankingFeedback\x12'.analytics.v1.GetRankingFeedbackRequest\x1a(.analytics.v1.GetRankingFeedbackResponseB;Z9github.com/petmatch/petmatch/internal/delivery/grpc/pb;pbb\x06proto3"

var (
	file_api_analytics_proto_rawDescOnce sync.Once
	file_api_analytics_proto_rawDescData []byte
)

func file_api_analytics_proto_rawDescGZIP() []byte {
	file_api_analytics_proto_rawDescOnce.Do(func() {
		file_api_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_analytics_proto_rawDesc), len(file_api_analytics_proto_rawDesc)))
	})
	return file_api_analytics_proto_rawDescData
}

var file_api_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_analytics_proto_goTypes = []any{
	(*GetMetricsRequest)(nil),          // 0: analytics.v1.GetMetricsRequest
	(*MetricCounter)(nil),              // 1: analytics.v1.MetricCounter
	(*ProfileMetric)(nil),              // 2: analytics.v1.ProfileMetric
	(*GetMetricsResponse)(nil),         // 3: analytics.v1.GetMetricsResponse
	(*GetExtendedStatsRequest)(nil),    // 4: analytics.v1.GetExtendedStatsRequest
	(*GetExtendedStatsResponse)(nil),   // 5: analytics.v1.GetExtendedStatsResponse
	(*GetRankingFeedbackRequest)(nil),  // 6: analytics.v1.GetRankingFeedbackRequest
	(*RankingFeedback)(nil),            // 7: analytics.v1.RankingFeedback
	(*GetRankingFeedbackResponse)(nil), // 8: analytics.v1.GetRankingFeedbackResponse
}
var file_api_analytics_proto_depIdxs = []int32{
	1, // 0: analytics.v1.ProfileMetric.counters:type_name -> analytics.v1.MetricCounter
	2, // 1: analytics.v1.GetMetricsResponse.items:type_name -> analytics.v1.ProfileMetric
	7, // 2: analytics.v1.GetRankingFeedbackResponse.items:type_name -> analytics.v1.RankingFeedback
	0, // 3: analytics.v1.AnalyticsService.GetMetrics:input_type -> analytics.v1.GetMetricsRequest
	4, // 4: analytics.v1.AnalyticsService.GetExtendedStats:input_type -> analytics.v1.GetExtendedStatsRequest
	6, // 5: analytics.v1.AnalyticsService.GetRankingFeedback:input_type -> analytics.v1.GetRankingFeedbackRequest
	3, // 6: analytics.v1.AnalyticsService.GetMetrics:output_type -> analytics.v1.GetMetricsResponse
	5, // 7: analytics.v1.AnalyticsService.GetExtendedStats:output_type -> analytics.v1.GetExtendedStatsResponse
	8, // 8: analytics.v1.AnalyticsService.GetRankingFeedback:output_type -> analytics.v1.GetRankingFeedbackResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_analytics_proto_init() }
func file_api_analytics_proto_init() {
	if File_api_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_analytics_proto_rawDesc), len(file_api_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_analytics_proto_goTypes,
		DependencyIndexes: file_api_analytics_proto_depIdxs,
		MessageInfos:      file_api_analytics_proto_msgTypes,
	}.Build()
	File_api_analytics_proto = out.File
	file_api_analytics_proto_goTypes = nil
	file_api_analytics_proto_depIdxs = nil
}
